---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: geerlingguy/docker-ubuntu2204-ansible:latest
    command: /lib/systemd/systemd
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:ro
    privileged: true
    pre_build_image: true
    tmpfs:
      - /run
      - /tmp
      - /run/lock
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
      collections_path: /home/terng/work/personal/wiphoo_ansible_frp/collections
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        frp_install_version: "0.63.0"
        frp_install_user: "frp"
        frp_install_group: "frp"
        frp_install_dir: "/usr/local/bin/frp"
        frp_install_config_dir: "/etc/frp"
        frp_install_log_dir: "/var/log/frp"
        frp_install_create_service: true
        frp_install_configure_firewall: false
        frp_install_cleanup_tmp: true
scenario:
  name: default
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
