---
- name: Destroy
  hosts: localhost
  connection: local
  gather_facts: false
  no_log: "{{ molecule_no_log }}"
  tasks:
    - name: Set async_dir for HOME env
      ansible.builtin.set_fact:
        ansible_async_dir: "{{ lookup('env', 'HOME') }}/.ansible_async/"
      when: lookup('env', 'HOME') | length > 0

    - name: Destroy molecule instance(s)
      community.docker.docker_container:
        name: "{{ item.name }}"
        state: absent
        force_kill: true
      with_items: "{{ molecule_yml.platforms }}"
      failed_when: false
