---
dependency:
  name: galaxy
driver:
  name: docker
platforms:
  - name: instance
    image: quay.io/ansible/creator-ee:latest
    command: /sbin/init
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
    pre_build_image: true
    cgroupns_mode: host
provisioner:
  name: ansible
  config_options:
    defaults:
      interpreter_python: auto_silent
      callbacks_enabled: profile_tasks, timer
      host_key_checking: false
      remote_tmp: /tmp
      gathering: implicit
      gather_facts: true
    ssh_connection:
      pipelining: true
      ssh_args: -o ControlMaster=auto -o ControlPersist=30m -o ConnectionAttempts=100 -o UserKnownHostsFile=/dev/null
  playbooks:
    converge: ../resources/playbook.yml
  inventory:
    group_vars:
      all:
        frp_install_version: "0.63.0"
        frp_install_user: "frp"
        frp_install_group: "frp"
        frp_install_dir: "/usr/local/bin/frp"
        frp_install_config_dir: "/etc/frp"
        frp_install_log_dir: "/var/log/frp"
        frp_install_create_service: true
        frp_install_configure_firewall: false
        frp_install_cleanup_tmp: true
scenario:
  name: ci
  test_sequence:
    - dependency
    - cleanup
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - cleanup
    - destroy
verifier:
  name: ansible
