---
galaxy_info:
  role_name: frp_install
  author: Wiphoo
  description: Installs frp (Fast Reverse Proxy) on supported systems.
  license: MIT
  min_ansible_version: "2.17"
  platforms:
    - name: Ubuntu
      versions:
        - focal
        - jammy
  galaxy_tags:
    - frp
    - proxy
    - installation

# Role dependencies (other roles this role depends on)
dependencies: []

# Allow duplicate handlers
allow_duplicates: true
