---
# Simple FRP Installation Example

- name: Install FRP Server
  hosts: frp_servers
  become: true
  vars:
    frp_version: "0.64.0"
  roles:
    - role: wiphoo.frp.frp_install
      vars:
        frp_install_files: ['frps']
        frp_install_create_service: true

- name: Install FRP Client
  hosts: frp_clients
  become: true
  vars:
    frp_version: "0.64.0"
  roles:
    - role: wiphoo.frp.frp_install
      vars:
        frp_install_files: ['frpc']
        frp_install_create_service: true
